### ISSUE TITLE
Collection entries with non-ascii titles are not decoded before saving to files

### ISSUE THREAD

**Issue by entr** [ADARTA/netlify-cms-components#17]
Thanks for the great product. I use it all the time.
One issue that I wish to report quite some time already.

How to reproduce:

```yml
...
fields:
  - label: Project name
    name: title
    widget: string
  - label: Content
    name: body
    widget: markdown
...
```
or any valid folder collection really as `title` field is required.

Enter non-ascii content for title.

![image](https://user-images.githubusercontent.com/191571/62633604-15b77900-b93d-11e9-89ee-67f5998c679f.png)

Results in such files being created:

![image](https://user-images.githubusercontent.com/191571/62633664-31228400-b93d-11e9-9809-3420bf261730.png)
